spring:
  profiles:
    include: local, jwt

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug

etc:
  base-url: ${BASE_URL}
  front-url: ${FRONT_URL}
  front-auth-success: ${FRONT_URL}/auth/success

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}
  secret: ${JWT_SECRET}

