spring:
  profiles:
    include: local, jwt, oauth, aws

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${FRONT_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 800MB

logging.level:
  kr.co.loopz: debug
  feign:
    client:
      logger: debug

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1_800_000}
    refresh: ${REFRESH_EXPIRATION:2_592_000_000}
  secret: ${JWT_SECRET:test1234tes1tte2st1234test1te!stte7stt@#e4sttes5ttest2testtest1234123415215161231}


cloud:
  aws:
    s3:
      bucket: loopz-bucket
    credentials:
      access-key: ${AWS_ACCESS_KEY:testkey}
      secret-key: ${AWS_SECRET_KEY:testsecret}
    region:
      static: ${AWS_REGION:test-region}
      auto: false
    stack:
      auto: false

etc:
  base-url: ${BASE_URL}
  base-ip: ${BASE_IP}
  #  front-url: ${FRONT_URL}
  google-profile-url: https://www.googleapis.com/userinfo/v2/me
  kakao-profile-url: https://kapi.kakao.com/v2/user/me
  kakao-token-url: https://kauth.kakao.com/oauth/token
  kakao:
    client-id: ${KAKAO_CLIENT}
    redirect-uri: ${FRONT_URL}/auth/v1/login/kakao

  user-service-url: ${USER_SERVICE_URL}
  authentication-service-url: ${AUTHENTICATION_SERVICE_URL}
  admin-service-url: ${ADMIN_SERVICE_URL}
  product-service-url: ${PRODUCT_SERVICE_URL}
  snap-service-url: ${SNAP_SERVICE_URL}
  magazine-service-url: ${MAGAZINE_SERVICE_URL}
  order-service-url: ${ORDER_SERVICE_URL}
  payment-service-url: ${PAYMENT_SERVICE_URL}
  search-service-url: ${SEARCH_SERVICE_URL}
